//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34011
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BettrDiet.WP8.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BettrDiet.WP8.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die add ähnelt.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Menu Item ähnelt.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MY APPLICATION ähnelt.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die abdominals ähnelt.
        /// </summary>
        public static string Daily_abs {
            get {
                return ResourceManager.GetString("Daily_abs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die biceps ähnelt.
        /// </summary>
        public static string Daily_biceps {
            get {
                return ResourceManager.GetString("Daily_biceps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die calf ähnelt.
        /// </summary>
        public static string Daily_calf {
            get {
                return ResourceManager.GetString("Daily_calf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die consumed calories ähnelt.
        /// </summary>
        public static string Daily_calories {
            get {
                return ResourceManager.GetString("Daily_calories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die chest ähnelt.
        /// </summary>
        public static string Daily_chest {
            get {
                return ResourceManager.GetString("Daily_chest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Date ähnelt.
        /// </summary>
        public static string Daily_date {
            get {
                return ResourceManager.GetString("Daily_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die fat ähnelt.
        /// </summary>
        public static string Daily_fat {
            get {
                return ResourceManager.GetString("Daily_fat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die forearms ähnelt.
        /// </summary>
        public static string Daily_forearms {
            get {
                return ResourceManager.GetString("Daily_forearms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die height ähnelt.
        /// </summary>
        public static string Daily_height {
            get {
                return ResourceManager.GetString("Daily_height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hips ähnelt.
        /// </summary>
        public static string Daily_hips {
            get {
                return ResourceManager.GetString("Daily_hips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die your current fitness ähnelt.
        /// </summary>
        public static string Daily_level {
            get {
                return ResourceManager.GetString("Daily_level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die low ähnelt.
        /// </summary>
        public static string Daily_level1 {
            get {
                return ResourceManager.GetString("Daily_level1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die super ähnelt.
        /// </summary>
        public static string Daily_level10 {
            get {
                return ResourceManager.GetString("Daily_level10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die measure ähnelt.
        /// </summary>
        public static string Daily_measure {
            get {
                return ResourceManager.GetString("Daily_measure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die muscle ähnelt.
        /// </summary>
        public static string Daily_muscle {
            get {
                return ResourceManager.GetString("Daily_muscle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die neck ähnelt.
        /// </summary>
        public static string Daily_neck {
            get {
                return ResourceManager.GetString("Daily_neck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die overview ähnelt.
        /// </summary>
        public static string Daily_overview {
            get {
                return ResourceManager.GetString("Daily_overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die shoulders ähnelt.
        /// </summary>
        public static string Daily_shoulders {
            get {
                return ResourceManager.GetString("Daily_shoulders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die statistics ähnelt.
        /// </summary>
        public static string Daily_statistics {
            get {
                return ResourceManager.GetString("Daily_statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die thighs ähnelt.
        /// </summary>
        public static string Daily_thighs {
            get {
                return ResourceManager.GetString("Daily_thighs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die daily data edit ähnelt.
        /// </summary>
        public static string Daily_title {
            get {
                return ResourceManager.GetString("Daily_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die diary ähnelt.
        /// </summary>
        public static string Daily_titleoverview {
            get {
                return ResourceManager.GetString("Daily_titleoverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die waist ähnelt.
        /// </summary>
        public static string Daily_waist {
            get {
                return ResourceManager.GetString("Daily_waist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die water ähnelt.
        /// </summary>
        public static string Daily_water {
            get {
                return ResourceManager.GetString("Daily_water", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die weight ähnelt.
        /// </summary>
        public static string Daily_weight {
            get {
                return ResourceManager.GetString("Daily_weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die wrists ähnelt.
        /// </summary>
        public static string Daily_writsts {
            get {
                return ResourceManager.GetString("Daily_writsts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your Goals ähnelt.
        /// </summary>
        public static string Goal_all {
            get {
                return ResourceManager.GetString("Goal_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit Goal ähnelt.
        /// </summary>
        public static string Goal_edit {
            get {
                return ResourceManager.GetString("Goal_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die achievments ähnelt.
        /// </summary>
        public static string Main_achievments {
            get {
                return ResourceManager.GetString("Main_achievments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die daily body stats ähnelt.
        /// </summary>
        public static string Main_dailydata {
            get {
                return ResourceManager.GetString("Main_dailydata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die data ähnelt.
        /// </summary>
        public static string Main_data {
            get {
                return ResourceManager.GetString("Main_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die food tracker ähnelt.
        /// </summary>
        public static string Main_foodtracker {
            get {
                return ResourceManager.GetString("Main_foodtracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die goals ähnelt.
        /// </summary>
        public static string Main_goals {
            get {
                return ResourceManager.GetString("Main_goals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die login ähnelt.
        /// </summary>
        public static string Main_Login {
            get {
                return ResourceManager.GetString("Main_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die logout ähnelt.
        /// </summary>
        public static string Main_Logout {
            get {
                return ResourceManager.GetString("Main_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die your health ähnelt.
        /// </summary>
        public static string Main_pivothealth {
            get {
                return ResourceManager.GetString("Main_pivothealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die workouts ähnelt.
        /// </summary>
        public static string Main_pivotworkout {
            get {
                return ResourceManager.GetString("Main_pivotworkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die quick access ähnelt.
        /// </summary>
        public static string Main_quickinfo {
            get {
                return ResourceManager.GetString("Main_quickinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die register ähnelt.
        /// </summary>
        public static string Main_Register {
            get {
                return ResourceManager.GetString("Main_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string Main_settings {
            get {
                return ResourceManager.GetString("Main_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die my training day ähnelt.
        /// </summary>
        public static string Main_trainingday {
            get {
                return ResourceManager.GetString("Main_trainingday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die new training day ähnelt.
        /// </summary>
        public static string Main_trainingdaynew {
            get {
                return ResourceManager.GetString("Main_trainingdaynew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die your latest weight ähnelt.
        /// </summary>
        public static string Main_weight {
            get {
                return ResourceManager.GetString("Main_weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die average nutrition facts ähnelt.
        /// </summary>
        public static string Nut_average {
            get {
                return ResourceManager.GetString("Nut_average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die day  ähnelt.
        /// </summary>
        public static string Nut_day {
            get {
                return ResourceManager.GetString("Nut_day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die diary ähnelt.
        /// </summary>
        public static string Nut_diary {
            get {
                return ResourceManager.GetString("Nut_diary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die energy ähnelt.
        /// </summary>
        public static string Nut_energy {
            get {
                return ResourceManager.GetString("Nut_energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die fat ähnelt.
        /// </summary>
        public static string Nut_fat {
            get {
                return ResourceManager.GetString("Nut_fat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die saturated fats ähnelt.
        /// </summary>
        public static string Nut_fatsat {
            get {
                return ResourceManager.GetString("Nut_fatsat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die fiber ähnelt.
        /// </summary>
        public static string Nut_fiber {
            get {
                return ResourceManager.GetString("Nut_fiber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die foodlist ähnelt.
        /// </summary>
        public static string Nut_food {
            get {
                return ResourceManager.GetString("Nut_food", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die fruit ähnelt.
        /// </summary>
        public static string Nut_fruit {
            get {
                return ResourceManager.GetString("Nut_fruit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die carbs ähnelt.
        /// </summary>
        public static string Nut_kh {
            get {
                return ResourceManager.GetString("Nut_kh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die food ähnelt.
        /// </summary>
        public static string Nut_list {
            get {
                return ResourceManager.GetString("Nut_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die meal ähnelt.
        /// </summary>
        public static string Nut_meal {
            get {
                return ResourceManager.GetString("Nut_meal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die overview ähnelt.
        /// </summary>
        public static string Nut_overview {
            get {
                return ResourceManager.GetString("Nut_overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die protein ähnelt.
        /// </summary>
        public static string Nut_prot {
            get {
                return ResourceManager.GetString("Nut_prot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die snacks ähnelt.
        /// </summary>
        public static string Nut_snacks {
            get {
                return ResourceManager.GetString("Nut_snacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die quota/actual ähnelt.
        /// </summary>
        public static string Nut_sollist {
            get {
                return ResourceManager.GetString("Nut_sollist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die spice ähnelt.
        /// </summary>
        public static string Nut_spice {
            get {
                return ResourceManager.GetString("Nut_spice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die vegetables ähnelt.
        /// </summary>
        public static string Nut_veg {
            get {
                return ResourceManager.GetString("Nut_veg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die accept ähnelt.
        /// </summary>
        public static string Reg_accept {
            get {
                return ResourceManager.GetString("Reg_accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die account ähnelt.
        /// </summary>
        public static string Reg_account {
            get {
                return ResourceManager.GetString("Reg_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die privacy policy ähnelt.
        /// </summary>
        public static string Reg_agb {
            get {
                return ResourceManager.GetString("Reg_agb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die age ähnelt.
        /// </summary>
        public static string Reg_age {
            get {
                return ResourceManager.GetString("Reg_age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die body ähnelt.
        /// </summary>
        public static string Reg_body {
            get {
                return ResourceManager.GetString("Reg_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die workouts per week ähnelt.
        /// </summary>
        public static string Reg_days {
            get {
                return ResourceManager.GetString("Reg_days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die your email adress ähnelt.
        /// </summary>
        public static string Reg_email {
            get {
                return ResourceManager.GetString("Reg_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die your email adress will be used to log you in later. you can not change it after you registered. ähnelt.
        /// </summary>
        public static string Reg_emailtxt {
            get {
                return ResourceManager.GetString("Reg_emailtxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die better endurance ähnelt.
        /// </summary>
        public static string Reg_endurance {
            get {
                return ResourceManager.GetString("Reg_endurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die reduce fat ähnelt.
        /// </summary>
        public static string Reg_fat {
            get {
                return ResourceManager.GetString("Reg_fat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die female ähnelt.
        /// </summary>
        public static string Reg_female {
            get {
                return ResourceManager.GetString("Reg_female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die height ähnelt.
        /// </summary>
        public static string Reg_height {
            get {
                return ResourceManager.GetString("Reg_height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die male ähnelt.
        /// </summary>
        public static string Reg_male {
            get {
                return ResourceManager.GetString("Reg_male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die minutes per workout ähnelt.
        /// </summary>
        public static string Reg_mins {
            get {
                return ResourceManager.GetString("Reg_mins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die build muscle ähnelt.
        /// </summary>
        public static string Reg_muscle {
            get {
                return ResourceManager.GetString("Reg_muscle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die nickname ähnelt.
        /// </summary>
        public static string Reg_nickname {
            get {
                return ResourceManager.GetString("Reg_nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die password ähnelt.
        /// </summary>
        public static string Reg_password {
            get {
                return ResourceManager.GetString("Reg_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Register Now! ähnelt.
        /// </summary>
        public static string Reg_register {
            get {
                return ResourceManager.GetString("Reg_register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die male or female? ähnelt.
        /// </summary>
        public static string Reg_sex {
            get {
                return ResourceManager.GetString("Reg_sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die how much time do you have for workouts? ähnelt.
        /// </summary>
        public static string Reg_timing {
            get {
                return ResourceManager.GetString("Reg_timing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die register ähnelt.
        /// </summary>
        public static string Reg_title {
            get {
                return ResourceManager.GetString("Reg_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die training ähnelt.
        /// </summary>
        public static string Reg_train {
            get {
                return ResourceManager.GetString("Reg_train", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die what is your workout goal? ähnelt.
        /// </summary>
        public static string Reg_trainfocus {
            get {
                return ResourceManager.GetString("Reg_trainfocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die weight ähnelt.
        /// </summary>
        public static string Reg_weight {
            get {
                return ResourceManager.GetString("Reg_weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die LeftToRight ähnelt.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die en-US ähnelt.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
    }
}
